version: '3'

services:
  flask:
    build:
      context: ./projectwork2024
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  react:
    build:
      context: ./pw2024js
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
